title: Fei
description: Exoplanets, Brown Dwarfs, Atmospheric Retrievals
author: Fei

theme: null

markdown: kramdown

permalink: pretty

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock